### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by vitaly-castLabs** [facebookexperimental/moq-encoder-player#14]
I was sure it was some new NodeJS framework or such when I stumbled upon `phyton` lol
https://github.com/facebookexperimental/moq-encoder-player/blob/main/README.md?plain=1#L274

**Comment by vitaly-castLabs** [comment]
I can create a PR fixing a few typos like this one I spotted...

**Comment by jordicenzano** [comment]
It would be great if you can do that. Thanks!

**Comment by jordicenzano** [comment]
I will close this since there is already a merged PR

If you see more typos please do not hesitate to create new PRs, really appreciated
