### ISSUE TITLE
Problem running moxygen/moq-encoder-player out of the box

### ISSUE THREAD

**Issue by YannickG-1951517** [facebookexperimental/moq-encoder-player#24]
I followed the instructions to set up a local instance of moxygen/moq-encoder-player but was unable to get any video output on my player.

I started up the Moxygen relay using the following command (with certificates for running it locally):
```
./_build/bin/moqdateserver -port 4433 -cert ../moq-encoder-player/certs/certificate.pem -key ../moq-encoder-player/cert
s/certificate.key --logging DBG
```
Then I proceeded to start the moq-encoder-player using:
```
./start-http-server-cross-origin-isolated.py
```
Now when visiting the webinterfaces for the encoder and the player I can see that my camera gets captured in the encoder. I proceeded to copy and paste the trackname from the encoder to the player and pressed start on both. Nothing happened.

I looked back and my cli with Moxygen running and saw the following errors:
```
I1215 13:57:35.628149 39278 MoQServer.cpp:145] /moq
E1215 13:57:35.628404 39278 MoQServer.h:89] Got error=ApplicationError: 268, 
I1215 13:57:35.628413 39278 MoQDateServer.cpp:252] terminateClientSession
V1215 13:57:35.628419 39278 MoQForwarder.h:134] subscribers_.size()=0
```
Now, I have been looking into what this application error could mean but I cannot seem to find it. I assume something goes wrong with the player part of the program and it never subscribes correctly (as the subscriber size states 0). 

Is there anything that I am doing wrong or is this something that has happened before?

**Comment by jordicenzano** [comment]
Thanks for your detailed explanation.

There a (known) current version incompatibility between moxygen and this repo. MoQ is moving fast recently and Moxygen is evolving at the same pace. We will try to fix that in following days

I will update this issue when fixed / tested

Details:
- This repo is expecting (tested with) moxygen version `0xff070002`, see [link](https://github.com/facebookexperimental/moq-encoder-player/blob/main/utils/moqt.js#L18)
- Curren moxygen is in version 7 ` 0xff000007`, see [link](https://github.com/facebookexperimental/moxygen/blob/main/moxygen/MoQFramer.h#L162)`

**Comment by jordicenzano** [comment]
This is fixed now!

Steps I followwed to test it in my MACOS machine:

# Start webserver for player (terminal 0)
```
cd ./moq-encoder-player
./create_self_signed_certs.sh
./start-http-server-cross-origin-isolated.py
```

# Build relay (follow more instructions in the repo readme) with commit id: `86e54d31d3dbddd430aee8f0da50e5dcf05c4d18`
```
cd moxygen
./build.sh
```

# Start relay (terminal1 )
./_build/bin/moqrelayserver -port 4433 -cert ../moq-encoder-player/certs/certificate.pem -key ../moq-encoder-player/certs/certificate.key -endpoint "/moq" --logging DBG1
```

# Generate live data from ffmpeg to a FIFO (terminal 2)
```
rm ~/Movies/fifo.flv
mkfifo ~/Movies/fifo.flv
ffmpeg -y -f lavfi -re -i smptebars=duration=300:size=320x200:rate=30 -f lavfi -re -i sine=frequency=1000:duration=300:sample_rate=48000 -pix_fmt yuv420p -c:v libx264 -b:v 180k -g 60 -keyint_min 60 -profile:v baseline -preset veryfast -c:a aac -b:a 96k -vf "drawtext=fontfile=/usr/share/fonts/dejavu-sans-fonts/DejaVuSans.ttf: text=\'Local time %{localtime\: %Y\/%m\/%d %H.%M.%S} (%{n})\': x=10: y=10: fontsize=12: fontcolor=white: box=1: boxcolor=0x00000099" -f flv ~/Movies/fifo.flv
```

# Start FLV Streamer (terminal 3)
```
./_build/bin/moqflvstreamerclient -input_flv_file ~/Movies/fifo.flv --logging DBG4
```

# Open webplayer
- Open chrome with `http://localhost:8080/src-player/index.html?local&verbose=1&host=moq://localhost:4433/moq`
- Set Namespace to `flvstreamer`
- Remove trackname

TODO: Still testing

**Comment by jordicenzano** [comment]
It seems this issue is solved, closing
